### Import libraries and Covid-19 data

In [1]:
import pandas as pd
from datetime import datetime

In [2]:
df = pd.read_csv("/home/andy/Documents/PythonExercises/Analytics_Report/data/Covid19Casos.csv")

### Removing unnecessary colums, only staying residencia_provincia_nombre, Count and fecha_diagnostico

In [3]:
df = df.drop(columns=['id_evento_caso', 'sexo', 'edad', 'edad_a침os_meses',
         'residencia_pais_nombre','residencia_departamento_nombre', 'carga_provincia_nombre',
         'fecha_inicio_sintomas', 'fecha_apertura', 'sepi_apertura',
         'fecha_internacion', 'cuidado_intensivo', 'fecha_cui_intensivo',
         'fallecido', 'fecha_fallecimiento', 'asistencia_respiratoria_mecanica',
         'carga_provincia_id', 'origen_financiamiento', 'clasificacion',
         'clasificacion_resumen', 'residencia_provincia_id', 'residencia_departamento_id', 'ultima_actualizacion'])
#df.reset_index(drop=True, inplace=True)

### Create column "year"

In [4]:
df["year"]=df["fecha_diagnostico"].str[0:4]
#df2["year"]=df2["year"].astype("int")

### Create new DF only with the rows beloging to the year 2021

In [5]:
df = df.loc[(df['year'] == "2021")]
df = df.sort_values(['residencia_provincia_nombre', 'fecha_diagnostico'], ascending=[1,0])
df.reset_index(drop=True, inplace=True)

### Create new DF with the Count column

In [6]:

#https://stackoverflow.com/questions/59631533/pandas-counting-rows-with-dates
#filter = df4["residencia_provincia_nombre"]=="CABA"
cnt = df.groupby(['fecha_diagnostico','residencia_provincia_nombre']).size().rename('Count')
result = df.drop_duplicates(subset=['fecha_diagnostico','residencia_provincia_nombre'])\
    .merge(cnt, left_on=['fecha_diagnostico','residencia_provincia_nombre'], right_index=True)
df = result.sort_values('fecha_diagnostico',ascending=False)

In [7]:
#EXAMPLE TO COUNT ALL CASES
#filter2 = df4["residencia_provincia_nombre"]=="CABA"
#cntCABA2 = df4.groupby('fecha_diagnostico').size().rename('Count')
#cntBA = df.groupby('Date').size().rename('Count')
#result2 = df4.drop_duplicates(subset='fecha_diagnostico')\
    #.merge(cntCABA2, left_on='fecha_diagnostico', right_index=True)
#result2.sort_values('fecha_diagnostico',ascending=False).head(10)

### Moving "fecha_diagnostivo" to the first column

In [8]:
cols = list(df.columns)
cols

def re_lista(x,y):
    l1 = x.copy()
    i1 = x.index(y)
    el1 = [l1[i1]]
    l1.remove(el1[0])
    return el1 + l1

In [9]:
df = df[re_lista(cols,'fecha_diagnostico')]
#df.tail()

        fecha_diagnostico residencia_provincia_nombre  year  Count
3751511        2021-01-01                        CABA  2021   1614
6629052        2021-01-01         Santiago del Estero  2021    161
6547746        2021-01-01                    Santa Fe  2021    384
3813730        2021-01-01                   Catamarca  2021     20
6891290        2021-01-01                     Tucum치n  2021    300

In [11]:
#https://stackoverflow.com/questions/38067704/how-to-change-the-datetime-format-in-pandas

df['fecha_diagnostico'] = pd.to_datetime(df.fecha_diagnostico)
df['fecha_diagnostico'] = df['fecha_diagnostico'].dt.strftime('%m/%d/%y')
#df

        fecha_diagnostico residencia_provincia_nombre  year  Count
0                05/31/21                Buenos Aires  2021   6266
4182049          05/31/21                     C칩rdoba  2021   1443
6548130          05/31/21         Santiago del Estero  2021    190
3813750          05/31/21                       Chaco  2021    195
3753125          05/31/21                   Catamarca  2021    264
...                   ...                         ...   ...    ...
3751511          01/01/21                        CABA  2021   1614
6629052          01/01/21         Santiago del Estero  2021    161
6547746          01/01/21                    Santa Fe  2021    384
3813730          01/01/21                   Catamarca  2021     20
6891290          01/01/21                     Tucum치n  2021    300

[3775 rows x 4 columns]

In [12]:
#https://stackoverflow.com/questions/17298313/python-pandas-convert-rows-as-column-headers
#https://towardsdatascience.com/a-step-by-step-guide-to-pandas-pivot-tables-e0641d0c6c70
#https://stackoverflow.com/questions/11346283/renaming-columns-in-pandas

df = df.pivot_table('Count', ['residencia_provincia_nombre'], 'fecha_diagnostico')
df.rename(columns=lambda x: x.replace("/0", "/").lstrip("0"), inplace=True)
#df

fecha_diagnostico,1/1/21,1/2/21,1/3/21,1/4/21,1/5/21,1/6/21,1/7/21,1/8/21,1/9/21,1/10/21,...,5/22/21,5/23/21,5/24/21,5/25/21,5/26/21,5/27/21,5/28/21,5/29/21,5/30/21,5/31/21
residencia_provincia_nombre,,,,,,,,,,,,,,,,,,,,,
Buenos Aires,3125,7538,5233,12252,14003,14462,14169,14528,12014,6436,...,16221,9384,18288,14560,26108,25654,24741,15544,8116,6266
CABA,1614,5918,8647,10819,11446,11160,9238,8994,8337,7649,...,7471,6125,9635,8845,11825,9474,11450,7075,5405,2847
Catamarca,20,290,337,298,298,373,338,324,383,208,...,800,619,624,633,697,882,771,679,373,264
Chaco,324,644,382,917,1009,1239,1081,973,827,291,...,1219,578,1100,795,1529,1681,1798,857,415,195
Chubut,70,419,195,1111,828,999,673,897,316,299,...,378,198,519,348,947,582,692,246,152,213
Corrientes,124,819,483,1074,1341,1252,1124,1453,1057,478,...,1213,770,2780,2293,2453,3003,2625,1508,1123,46
C칩rdoba,290,2639,911,3851,4953,5613,4891,4648,3635,759,...,7032,2211,8226,5881,10258,11991,10241,6996,2091,1443
Entre R칤os,168,701,266,938,888,1072,1020,1063,717,268,...,1181,228,937,471,1530,1700,1470,874,233,286
Formosa,87,238,314,405,304,512,476,252,142,110,...,2045,1551,1973,1876,2309,2661,2584,1585,1143,667
Jujuy,13,115,84,210,170,234,209,214,158,54,...,492,334,426,310,600,792,866,537,249,237
La Pampa,405,594,501,693,804,741,841,1039,514,369,...,764,726,1136,845,1321,1026,1028,781,419,247
La Rioja,48,53,52,99,128,116,110,214,182,95,...,154,134,141,162,326,240,382,156,106,38
Mendoza,142,548,212,836,885,898,882,847,731,213,...,1488,517,1160,748,2144,1992,2063,1203,517,754
Misiones,37,216,101,171,200,213,120,200,320,157,...,197,165,329,444,433,449,357,173,267,330
Neuqu칠n,260,496,300,875,793,671,686,1050,749,436,...,908,915,869,979,988,1165,973,786,679,305
R칤o Negro,128,366,133,761,732,766,652,721,559,102,...,700,262,732,412,1039,877,1031,542,171,435
SIN ESPECIFICAR,26,62,53,84,120,124,122,107,89,43,...,99,62,110,106,192,152,188,96,39,41
Salta,23,186,82,313,248,342,227,393,213,94,...,931,400,1045,712,1178,1303,1325,768,556,394
San Juan,37,149,93,950,543,512,543,607,206,56,...,460,266,721,640,1054,679,636,232,150,265
San Luis,147,261,295,482,437,584,563,766,862,668,...,1821,1207,1090,985,1481,1551,1430,1501,1031,337
Santa Cruz,134,613,300,911,1039,932,834,776,800,636,...,375,178,419,473,478,541,475,310,236,224
Santa Fe,384,1659,969,2540,3292,3506,3085,3293,1999,1218,...,4140,2558,4630,3870,6108,6135,6051,4046,2044,1568
Santiago del Estero,161,194,284,419,741,622,727,721,741,472,...,834,306,638,688,749,930,811,762,374,190
Tierra del Fuego,54,241,151,226,240,228,277,213,230,154,...,133,119,211,126,158,185,165,87,46,76
Tucum치n,300,608,726,1200,1120,1265,1387,1618,1043,882,...,2154,1548,2421,1981,3038,3065,3170,2296,1578,350

In [13]:
df.to_csv('/home/andy/Documents/PythonExercises/Analytics_Report/dataCovid19Cases_FINAL.csv')